#Configuraciones generales de la aplicaci?n
spring.application.name=retobci
server.port=8080

# Expresión regular para contraseñas (mínimo 6 caracteres, acepta letras, números y caracteres especiales)
user.password.pattern=^(?=.*[a-zA-Z])(?=.*[0-9]).{6,}$

# Expresión regular para email
user.email.pattern=^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$

# Configuraci?n de base de datos H2
spring.datasource.url=jdbc:h2:mem:retodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=create-drop

logging.level.org.springframework=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.aop=DEBUG

# Log de sentencias SQL de Hibernate
logging.level.org.hibernate.SQL=DEBUG
# Log de los parámetros de las sentencias
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# JWT Secret Key (256 bits)
security.jwt.secret-key=4b4947f47d2c479f4db6006f26b4b00265888d2c7a4a6e90477a4a3722bc61e0
# 12h en millisecond
security.jwt.expiration-time=43200000

# OpenAPI / Swagger UI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

